### ISSUE TITLE
Enchants get deleted when you leave and login the world if you place them on the ground after relogging

### ISSUE THREAD

**Issue by ElfyTR** [RubixDev/EnchantedShulkers#6] opened 2022-09-22 10:14 UTC
1 you enter the world
2 you play and get your shulkers enchanted place and break them several times nothing happens
3 you leave the world
4 you enter the world again place the shulkers down and break them and boom suddenly they are unenchanted. 
i have to re enchant them every session if i dont reenchant every one with it the second i put it on the ground its gone

**Comment by RubixDev** [comment] 2022-09-22 10:26
Sorry, I cannot reproduce this issue. Can you provide a bit more information?
- Singleplayer or Multiplayer
- List of used mods with versions
- MC version
- Survival or creative mode

**Comment by RubixDev** [comment] 2023-01-22 16:26
Sorry, I have still never encountered this problem myself, but seemingly someone else in #9 did. Could you try to work on a minimal reproducible setup?

**Comment by RubixDev** [comment] 2024-02-25 11:07
Alright so this was an incompatibility with packed-inventory and it has been reported and resolved on their side at the end of last year: https://github.com/Kir-Antipov/packed-inventory/issues/7. This issue should be fixed when using version 0.3.0 or newer of the packed-inventory mod.

**Closed by RubixDev** 2024-02-25 11:07 UTC
Labels: bug, help wanted, good first issue
