### ISSUE TITLE
Severe incompatibility with Reinforced Shulkers mod.

### ISSUE THREAD

**Issue by GeneralZenon** [RubixDev/EnchantedShulkers#28] opened 2023-10-20 17:26 UTC
It looks that the siphon mod applies to the normal amount of slots which are found in a regular shulker box as intended. However Reinforced shulkers have an increased capacity, especially when fully upgraded.

What seems to happen is that if items are placed beyond the normal capacity of a shulker box and you try it with the siphon enchantment, there is a chance for items to be deleted from the shulker box which is very unfortunate.

I believe this would be a very nice synergy between these two mods, since upgrading shulker boxes in this mod isn't too game breaking and requires some effort, especially since it uses the smithing table and upgrade templates like netherite armor does.

Reinforced shulkers: https://modrinth.com/mod/reinforced-shulker-boxes

If this is something of interest for the mod and author and helps then i'm very glad, i'm not going to beg nor demand support for this issue since you have your own lives and things to deal with, just wanted to shine some light on the situation i found myself in. I'll continue to use this mod since it's something i wanted for quite a while in minecraft, keep up the great work and have a lovely day ^^.

**Comment by RubixDev** [comment] 2023-10-23 07:12
I am definitely interested in having the mods be compatible, I just currently lack the time and motivation to work on this. Also I will close this issue as a duplicate of https://github.com/RubixDev/EnchantedShulkers/issues/24

**Closed by RubixDev** 2023-10-23 07:12 UTC
