### ISSUE TITLE
enchantment removed when place it on ground and pick up again

### ISSUE THREAD

**Issue by jarocajavi** [RubixDev/EnchantedShulkers#9] opened 2022-11-19 23:58 UTC
For now my "fix" is use another mod to open the shulker without place it.
Thanks for your work.

**Comment by RubixDev** [comment] 2023-01-04 11:56
i'm sorry for the very late reply. does this always happen? i assume you are in survival mode? what tool do you use to break the shulker box?

**Comment by jarocajavi** [comment] 2023-01-04 18:34
None, it is required any specific tool?

**Comment by RubixDev** [comment] 2023-01-04 19:57
In theory not and in my testing it works just fine with and without pickaxe, but I just wanted to know in case it does make a difference. Also I'm closing this issue as i suspect it's a duplicate of #6.

**Closed by RubixDev** 2023-01-04 19:57 UTC
Labels: bug, question
